/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#include <string.h>
#include "europa.h"

void
_ORBIT_skel_EuropaAI_Europa_inputChat(POA_EuropaAI_Europa * _ORBIT_servant,
				      GIOPRecvBuffer * _ORBIT_recv_buffer,
				      CORBA_Environment * ev,
				      void (*_impl_inputChat)
				      (PortableServer_Servant _servant,
				       CORBA_char * text,
				       CORBA_Environment * ev))
{
   CORBA_char *text;

   {				/* demarshalling */
      guchar *_ORBIT_curptr;
      register CORBA_unsigned_long _ORBIT_tmpvar_2;
      CORBA_unsigned_long _ORBIT_tmpvar_3;

      _ORBIT_curptr = GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur;
      if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 _ORBIT_tmpvar_3 =
	    (CORBA_unsigned_long)
	    GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	    _ORBIT_curptr += 4;
	 text = (void *) _ORBIT_curptr;
	 _ORBIT_curptr += sizeof(text[_ORBIT_tmpvar_2]) * _ORBIT_tmpvar_3;
      } else {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 _ORBIT_tmpvar_3 = *((CORBA_unsigned_long *) _ORBIT_curptr);
	 _ORBIT_curptr += 4;
	 text = (void *) _ORBIT_curptr;
	 _ORBIT_curptr += sizeof(text[_ORBIT_tmpvar_2]) * _ORBIT_tmpvar_3;
      }
   }
   _impl_inputChat(_ORBIT_servant, text, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (ev->_major == CORBA_NO_EXCEPTION) {
      } else
	 ORBit_send_system_exception(_ORBIT_send_buffer, ev);
      giop_send_buffer_write(_ORBIT_send_buffer);
      giop_send_buffer_unuse(_ORBIT_send_buffer);
   }
}
static ORBitSkeleton
get_skel_EuropaAI_Europa(POA_EuropaAI_Europa * servant,
			 GIOPRecvBuffer * _ORBIT_recv_buffer, gpointer * impl)
{
   gchar *opname = _ORBIT_recv_buffer->message.u.request.operation;

   switch (opname[0]) {
     case 'i':
      if (strcmp((opname + 1), "nputChat"))
	 break;
      *impl = (gpointer) servant->vepv->EuropaAI_Europa_epv->inputChat;
      return (ORBitSkeleton) _ORBIT_skel_EuropaAI_Europa_inputChat;
      break;
     default:
      break;
   }
   return NULL;
}

static void
init_local_objref_EuropaAI_Europa(CORBA_Object obj,
				  POA_EuropaAI_Europa * servant)
{
   obj->vepv[EuropaAI_Europa__classid] = servant->vepv->EuropaAI_Europa_epv;
}
void
POA_EuropaAI_Europa__init(PortableServer_Servant servant,
			  CORBA_Environment * env)
{
   static const PortableServer_ClassInfo class_info =
      { (ORBit_impl_finder) & get_skel_EuropaAI_Europa,
	 "IDL:EuropaAI/Europa:1.0",
	 (ORBit_local_objref_init) & init_local_objref_EuropaAI_Europa };

   PortableServer_ServantBase__init(((PortableServer_ServantBase *) servant),
				    env);
   ORBIT_OBJECT_KEY(((PortableServer_ServantBase *) servant)->_private)->
      class_info = (PortableServer_ClassInfo *) & class_info;
   if (!EuropaAI_Europa__classid)
      EuropaAI_Europa__classid = ORBit_register_class(&class_info);
}

void
POA_EuropaAI_Europa__fini(PortableServer_Servant servant,
			  CORBA_Environment * env)
{
   PortableServer_ServantBase__fini(servant, env);
}
