/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#include <string.h>
#include "europa.h"

#if (TC_IMPL_TC_EuropaAI_Europa == ORBIT_FILE_ID_europa) && !defined(TC_DEF_TC_EuropaAI_Europa)
#define TC_DEF_TC_EuropaAI_Europa 1
const struct CORBA_TypeCode_struct TC_EuropaAI_Europa_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_objref, "Europa", "IDL:EuropaAI/Europa:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
CORBA_unsigned_long EuropaAI_Europa__classid = 0;
